class GroceryListFormatter

def self.normal
  ['Allspice', 
  'Arrowroot starch',
  'Basil',
  'Bay leaves',
  'Chili powder',
  'Cinnamon',
  'garlic',
  'Coriander',
  'Cream of tartar',
  'Cumin',
  'Curry',
  'Dill',
  'Fennel',
  'Five-spice powder',
  'Garlic powder',
  'Ginger',
  'Marjoram',
  'Mint',
  'Mustard',
  'Nutmeg',
  'Onion',
  'Oregano',
  'Paprika',
  'Pepper',
  'cayenne',
  'Peppercorns',
  'Poppy seeds',
  'Rosemary',
  'Sage',
  'Salt',
  'Sesame seeds',
  'Tarragon',
  'Thyme',
  'Turmeric',
  'Vanilla',
  'Baking Powder',
  'Baking Soda',
  'Brown Sugar',
  'Brownie Mix',
  'Cake Mix',
  'Cocoa',
  'Cornstarch',
  'Flour',
  'Sugar',
  'Vanilla Extract',
  'Bread Crumbs',
  'Biscuits',
  'Bread',
  'Buns',
  'Rolls',
  'Soup',
  'Canned Tuna',
  'BBQ Sauce',
  'Cooking Spray',
  'Honey',
  'Horseradish',
  'Hot sauce',
  'Jelly',
  'Ketchup',
  'Mayonnaise',
  'Mustard',
  'Olive Oil',
  'Peanut Butter',
  'Salad Dressing',
  'Salsa',
  'Soy Sauce',
  'Vegetable Oil',
  'Worcestershire',
  'Dairy',
  'Butter',
  'Cheese',
  'Cottage Cheese',
  'Cream',
  'Cream Cheese',
  'Eggs',
  'Milk',
  'Sour Cream',
  'Yogurt',
  'Water',
  'Coffee',
  'Juice',
  'Soda Pop',
  'Sports Drinks',
  'Tea',
  'French Fries',
  'Frozen Vegetables',
  'Ice Cream',
  'Pizza',
  'Pasta',
  'Rice',
  'Spaghetti Sauce',
  'Meats',
  'Beef',
  'Chicken',
  'Fish',
  'Pork',
  'Apple',
  'Asparagus',
  'Bananas',
  'Berries',
  'Broccoli',
  'Cabbage',
  'Carrots',
  'Cauliflower',
  'Celery',
  'Corn',
  'Garlic',
  'Grapes',
  'Lemons',
  'Lettuce',
  'Limes',
  'Melons',
  'Mushrooms',
  'Nectarines',
  'Onions',
  'Oranges',
  'Peaches',
  'Pears',
  'Plums',
  'cornstarch',
  'rice wine vinegar',
  'sesame oil',
  'hoisin sauce',
  'scallion',
  'Tomatoes']
end

  def self.check_name(string)
    array = normal.select do |ingredient|
      string.downcase.include?(ingredient.downcase)
    end
    array.first
  end

end
